<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags-->
    <meta http-equiv="Cache-Control" content="max-age=0">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <!-- Color theme for statusbar -->
    <meta name="theme-color" content="#2196f3">
    <!-- Your app title -->
    <title>Smart Remote</title>
    <!-- Path to your custom app styles-->
    <link rel="stylesheet" href="css/app.min.css">
  </head>
  <body>
    <div id="app">
      <!-- Statusbar overlay -->
      <div class="statusbar"></div>

      <div class="panel panel-left panel-cover">
        <div class="navbar no-shadow">
          <div class="navbar-inner">
            <div class="title" id="username">Username</div>
          </div>
        </div>
        
        <div class="list">
          <ul>
            <li>
              <a href="#" class="item-link item-content panel-close" id="logout">
                <div class="item-media"><i class="fa fa-lightbulb-o size-25" aria-hidden="true"></i></div>
                <div class="item-inner">
                  <div class="item-title">Logout</div>
                </div>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <!-- Your main view, should have "view-main" class -->
      <div class="view view-main">
      </div>

    </div>
    <!-- <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script> -->
    <script type="text/javascript" src="js/app.min.js"></script>
  </body>
</html> 
